package com.training.nmusabirova.hw8task2;

public enum Skills {
    BASIC_LEVEL_OF_PC_OWNERSHIP,
    DRAWING_UP_ESTIMATED_DOCUMENTATION,
    ECONOMIC_EVALUATION_OF_PROJECT,
    FINISHING_WORKS,
    KNOWLEDGE_OF_ENGLISH,
    KNOWLEDGE_OF_MATERIAL_PROPERTIES,
    MANAGEMENT_OF_CONSTRUCTION_BRIGADE,
    READ_DRAWINGS,
    RECONSTRUCTION_WORKS,
    REPLACEMENT_ELECTRICAL_WIRING,
    SAFETY_KNOWLEDGE,
    TEAMWORK,
    TECHNICAL_EVALUATION_OF_PROJECT,
    WORK_WITH_POWER_TOOLS
}
